In [1]:
import numpy as np

In [2]:
narray = np.array([1,2,3,4,5])

In [3]:
narray

array([1, 2, 3, 4, 5])

In [4]:
import numpy as np

In [8]:
array1 = np.array([3,4,5,6],dtype="int8")

In [9]:
type(array1)

numpy.ndarray

In [11]:
#shape
array1.shape

(4,)

Array Operations

In [14]:
n1 = np.array([3,4,2,1])
n2 = np.array([2,5,6,7])

In [15]:
n1+n2

array([5, 9, 8, 8])

In [16]:
np.sqrt(n1)

array([1.73205081, 2.        , 1.41421356, 1.        ])

In [17]:
np.sqrt(n2)

array([1.41421356, 2.23606798, 2.44948974, 2.64575131])

#### Indexing and Slicing (Accessing elements of array)

In [26]:
## 1d array (nd array)
a1 = np.array([1,2,4,5,7,8])
#indexing
print(a1[3])
#slicing
print(a1[1:4])

5
[2 4 5]


In [29]:
###Boolen indexing
a1[a1>3]

array([4, 5, 7, 8])

reshaping of array

In [30]:
rarray = np.arange(10)
rarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
len(rarray)

10

In [38]:
rarray.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
reshape = rarray.reshape((2,5))

Matrix multilication

In [42]:
n1 = np.ones((3,2))
n2 = np.array([
    [3,4,5],
    [5,2,1]
])
print(n1.shape)
print(n2.shape)

(3, 2)
(2, 3)


In [43]:
np.dot(n1,n2)

array([[8., 6., 6.],
       [8., 6., 6.],
       [8., 6., 6.]])